// <auto-generated />
using System;
using Darbuotojai.Architecture.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Darbuotojai.Architecture.Infra.Data.Migrations
{
    [DbContext(typeof(DarbuotojaiDbContext))]
    [Migration("20200627002005_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.6.20312.4");

            modelBuilder.Entity("Darbuotojai.Domain.Models.Darbuotojas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktyvus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AsmensKodas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gatve")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GimimoData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Miestas")
                        .HasColumnType("TEXT");

                    b.Property<int>("NamoNumeris")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PastoKodas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pavardė")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vardas")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Darbuotojai");
                });
#pragma warning restore 612, 618
        }
    }
}
